
const $=s=>document.querySelector(s), money=n=>"₹"+Math.round(n).toLocaleString("en-IN");
function nav(){return `<div class="top">FREE DELIVERY ON ORDERS ₹899+ &nbsp; • &nbsp; 5 SHREHA POINTS ON ORDERS ₹699+</div><div class="nav"><div class="navin"><a class="logo" href="index.html"><img class="brandmark" src="assets/shreha-mark-dark.png" alt="SHREHA logo mark"><span>SHREHA</span></a><div class="links"><a href="shop.html">Shop</a><a href="category.html?cat=Mini Dresses">Dresses</a><a href="category.html?cat=Jeans">Jeans</a><a href="category.html?cat=Co-ord Sets">Co-ords</a><a href="category.html?cat=Gym Wear">Active</a><a href="category.html?cat=Lounge Wear">Lounge</a><a href="gift.html">Gifting</a></div><div class="icons"><a class="ico" href="wishlist.html">♡</a><a class="ico" href="cart.html">🛍</a><a class="ico" href="login.html">♙</a></div></div></div>`}
function footer(){return `<footer class="footer"><div class="footin"><div><h3>SHREHA</h3><p>Premium women's clothing with a soft, feminine point of view.</p></div><div><b>SHOP</b><a href="shop.html">All Clothing</a><a href="category.html?cat=Mini Dresses">Dresses</a><a href="category.html?cat=Jeans">Jeans</a><a href="category.html?cat=Co-ord Sets">Co-ords</a></div><div><b>HELP</b><a href="account.html">My Account</a><a href="messages.html">Message Us</a><a href="gift.html">Gifting</a></div><div><b>SHREHA CLUB</b><p>50 points → free hamper<br>100 points → custom gift</p></div></div></footer>`}
function layout(c){$("#app").innerHTML=nav()+c+footer()}
function card(p){let w=wish().includes(p.id);return `<div class="card"><span class="badge">${p.offer}% OFF</span><button type="button" class="heart" onclick="event.preventDefault();event.stopPropagation();toggleWish(${p.id})">${w?"♥":"♡"}</button><a href="product.html?id=${p.id}"><div class="pic"><img src="${p.img}" alt="${p.name}"></div><div class="info"><span class="muted">${p.cat}</span><h3>${p.name}</h3><span class="price">${money(p.price*(1-p.offer/100))}</span><span class="old">${money(p.price)}</span></div></a></div>`}
function grid(a){return `<div class="grid">${a.filter(p=>!p.hidden).map(card).join("")}</div>`}
function home(){
const ps=products();
const sectionMap=[["Mini Dresses","Mini Dresses"],["Midi Dresses","Midi Dresses"],["Floral Dresses","Floral Dresses"],["Jeans","Jeans"],["Tops","Tops"],["Co-ord Sets","Co-ord Sets"],["Gym Wear","Gym Wear"],["Lounge Wear","Lounge Wear"],["Night Dresses","Night Dresses"],["T-Shirts","T-Shirts"],["Shirts","Shirts"],["Trousers","Trousers"],["Skirts","Skirts"],["Jackets","Jackets"]];
const sectionCards=sectionMap.map(([label,cat])=>{const p=ps.find(x=>x.cat===cat&&!x.hidden);return p?`<a class="home-section-card" href="category.html?cat=${encodeURIComponent(cat)}"><img src="${p.img}" alt="${label}"><div><span class="eyebrow">SHREHA EDIT</span><h3>${label}</h3><p>Explore the collection →</p></div></a>`:"";}).join("");
const dressCats=["Mini Dresses","Midi Dresses","Floral Dresses"];
const hero=ps.filter(p=>dressCats.includes(p.cat)&&!p.hidden).slice(0,12);
const heroSlides=hero.map((p,i)=>`<a class="hero-slide ${i===0?'active':''}" href="product.html?id=${p.id}"><img src="${p.img}" alt="${p.name}"><div class="slide-shade"></div><div class="slide-caption"><span>${p.cat}</span><b>${p.name}</b><em>SHOP THIS LOOK →</em></div></a>`).join("");
const heroDots=hero.map((p,i)=>`<button class="hero-dot ${i===0?'active':''}" aria-label="Slide ${i+1}" onclick="heroGo(${i});event.preventDefault();event.stopPropagation()"></button>`).join("");
layout(`<section class="hero hero-slideshow-wrap"><div class="hero-slideshow" id="heroSlideshow"><div class="hero-slides">${heroSlides}</div><div class="hero-overlay"><div class="hero-overlay-copy"><span class="eyebrow">THE NEW SHREHA EDIT</span><h1>Dress like<br>you mean it.</h1><p>Feminine dresses, beautiful colours and effortless silhouettes made for every mood.</p><a class="btn primary" href="category.html?cat=Mini Dresses">SHOP DRESSES</a></div></div><button class="hero-arrow prev" onclick="heroPrev();event.preventDefault();event.stopPropagation()" aria-label="Previous slide">‹</button><button class="hero-arrow next" onclick="heroNext();event.preventDefault();event.stopPropagation()" aria-label="Next slide">›</button><div class="hero-dots">${heroDots}</div><div class="hero-progress"><span id="heroProgress"></span></div></div></section><section class="container"><div class="sectionhead"><div><span class="eyebrow">SHOP BY CATEGORY</span><h2>One wardrobe. Every mood.</h2></div><a href="shop.html">View all →</a></div><div class="home-sections">${sectionCards}</div></section><section class="container"><div class="sectionhead"><div><span class="eyebrow">FRESH PICKS</span><h2>New arrivals</h2></div><a href="shop.html">View all →</a></div>${grid(ps.filter(p=>!p.hidden).slice(0,8))}</section><section class="container"><div class="collections"><a class="collection cream" href="category.html?cat=Jeans"><h3>Denim Days</h3><p>Jeans, shirts and jackets.</p></a><a class="collection pink" href="category.html?cat=Night Dresses"><h3>After Hours</h3><p>Soft night dresses & lounge sets.</p></a><a class="collection lav" href="category.html?cat=Jackets"><h3>Layer It</h3><p>Jackets for every season.</p></a></div></section>`);
heroInit();
}
let heroIndex=0,heroTimer=null;
function heroSet(i){
 const slides=[...document.querySelectorAll(".hero-slide")];
 const dots=[...document.querySelectorAll(".hero-dot")];
 if(!slides.length)return;
 heroIndex=(i+slides.length)%slides.length;
 slides.forEach((el,n)=>el.classList.toggle("active",n===heroIndex));
 dots.forEach((el,n)=>el.classList.toggle("active",n===heroIndex));
 const bar=document.getElementById("heroProgress");
 if(bar){bar.style.transition="none";bar.style.width="0%";requestAnimationFrame(()=>{requestAnimationFrame(()=>{bar.style.transition="width 4.5s linear";bar.style.width="100%"})})}
}
function heroGo(i){heroSet(i);heroStart();}
function heroNext(){heroSet(heroIndex+1);heroStart();}
function heroPrev(){heroSet(heroIndex-1);heroStart();}
function heroStart(){
 if(heroTimer)clearInterval(heroTimer);
 heroTimer=setInterval(()=>heroSet(heroIndex+1),4500);
}
function heroInit(){
 const wrap=document.getElementById("heroSlideshow");
 if(!wrap)return;
 heroIndex=0;
 heroSet(0);
 heroStart();
 wrap.addEventListener("mouseenter",()=>{if(heroTimer)clearInterval(heroTimer)});
 wrap.addEventListener("mouseleave",heroStart);
}
function shop(){let q=new URLSearchParams(location.search),cat=q.get("cat")||"All",ps=products().filter(p=>cat==="All"||p.cat===cat);layout(`<div class="title"><span class="eyebrow">SHREHA CLOTHING</span><h1>${cat==="All"?"The Full Collection":cat}</h1><p class="muted">XS–XXXL • multiple colours • prints • patterns</p></div><section class="container"><div class="shop"><aside class="filters"><b>CATEGORIES</b>${CATS.map(c=>`<a href="${c==="All"?"shop.html":"category.html?cat="+encodeURIComponent(c)}">${c}</a>`).join("")}</aside><main><div class="toolbar"><span class="muted">${ps.length} styles</span><select class="select" onchange="sortIt(this.value)"><option value="featured">Featured</option><option value="low">Price low to high</option><option value="high">Price high to low</option></select></div><div id="products">${grid(ps)}</div></main></div></section>`)}
function sortIt(v){let p=products();if(v==="low")p.sort((a,b)=>a.price-b.price);if(v==="high")p.sort((a,b)=>b.price-a.price);$("#products").innerHTML=grid(p)}
function toggleWish(id){let w=wish();if(w.includes(id)){w=w.filter(x=>x!==id)}else{if(w.length>=3){alert("You can keep up to 3 wishlist items.");return}w.push(id)}saveWish(w);const btn=document.querySelector(`.heart[onclick*="${id}"]`);if(btn)btn.textContent=w.includes(id)?"♥":"♡";if(document.body.dataset.page==="wishlist")wishlistPage()}
function product(){let id=+new URLSearchParams(location.search).get("id"),p=products().find(x=>x.id===id);if(!p)return shop();layout(`<section class="container"><div class="detail"><img class="detailimg" src="${p.img}" alt="${p.name}"><div><span class="eyebrow">${p.cat}</span><h1>${p.name}</h1><div class="price" style="font-size:24px">${money(p.price*(1-p.offer/100))} <span class="old">${money(p.price)}</span></div><p class="muted">${p.stock} available • ${p.offer}% offer</p><hr><h4>SIZE</h4><div class="sizes">${p.sizes.map(s=>`<button onclick="this.classList.toggle('active')">${s}</button>`).join("")}</div><p class="muted">Select your preferred size before adding to bag.</p><div style="display:flex;gap:10px;margin-top:22px"><button class="btn primary" onclick="addCart(${p.id})">ADD TO BAG</button><button class="btn soft" type="button" onclick="toggleWish(${p.id});this.textContent=wish().includes(${p.id})?"♥ WISHLIST":"♡ WISHLIST"">♡ WISHLIST</button></div><div class="notice">Free delivery on orders ₹899 and above. Orders below ₹899 have ₹30 delivery charges.</div></div></div></section>`)}
function addCart(id){let c=cart(),i=c.find(x=>x.id===id);i?i.qty++:c.push({id,qty:1});saveCart(c);location.href="cart.html"}
function cartPage(){let c=cart(),ps=products(),rows=c.map(i=>{let p=ps.find(x=>x.id===i.id);return p?`<div class="cartrow"><img class="thumb" src="${p.img}"><div><b>${p.name}</b><div class="muted">${p.cat}</div></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button>${i.qty}<button onclick="changeQty(${p.id},1)">+</button></div><b>${money(p.price*(1-p.offer/100)*i.qty)}</b></div>`:""}).join(""),sub=c.reduce((s,i)=>{let p=ps.find(x=>x.id===i.id);return s+(p?p.price*(1-p.offer/100)*i.qty:0)},0),del=sub>=899||sub===0?0:30;layout(`<div class="title"><span class="eyebrow">YOUR BAG</span><h1>Shopping Bag</h1></div><section class="container"><div class="twocol"><div class="panel">${rows||"<p>Your bag is empty.</p>"}</div><div class="panel summary"><h3>Order Summary</h3><div class="sum"><span>Subtotal</span><b>${money(sub)}</b></div><div class="sum"><span>Delivery</span><b>${del?"₹30":"FREE"}</b></div><div class="sum total"><span>Total</span><span>${money(sub+del)}</span></div><a class="btn primary" style="width:100%" href="${sub?"checkout.html":"shop.html"}">CHECKOUT</a></div></div></section>`)}
function changeQty(id,d){let c=cart(),i=c.find(x=>x.id===id);i.qty+=d;if(i.qty<1)c=c.filter(x=>x.id!==id);saveCart(c);cartPage()}
function wishlistPage(){let a=products().filter(p=>wish().includes(p.id));layout(`<div class="title"><span class="eyebrow">YOUR SAVED EDIT</span><h1>Wishlist</h1><p class="muted">Choose up to 3 favourites and SHREHA can personalise suggestions around them.</p></div><section class="container">${a.length?grid(a):"<div class='panel'>Your wishlist is empty.</div>"}</section>`)}
function account(){let u=user();layout(`<section class="container"><div class="panel" style="max-width:520px;margin:auto"><span class="eyebrow">MY SHREHA</span><h1>${u?"Welcome, "+u.name:"Your SHREHA Account"}</h1>${u?`<p>${u.email}</p><div class="notice">SHREHA POINTS: <b>${u.points||0}</b><br>${u.points>=100?"Your custom gift is unlocked.":u.points>=50?"Your free hamper is unlocked.":"Earn 5 points on every order of ₹699+."}</div><a class="btn primary" href="messages.html">MESSAGE SHREHA</a> <button class="btn soft" onclick="logout()">LOG OUT</button>`:`<div class="field"><label>NAME</label><input id="name"></div><div class="field"><label>EMAIL</label><input id="email" type="email"></div><div class="field"><label>PASSWORD</label><input id="password" type="password"></div><button class="btn primary" style="width:100%" onclick="location.href='login.html'">CREATE ACCOUNT / SIGN IN</button>`}</div></section>`)}
function commonLogin(){
const email=(document.getElementById("loginEmail")||{}).value.trim().toLowerCase();
const pass=(document.getElementById("loginPass")||{}).value||"";
const name=(document.getElementById("loginName")||{}).value.trim();
const phone=(document.getElementById("loginPhone")||{}).value.trim();
if(!name)return alert("Please enter your name.");
if(!/^[A-Za-z0-9._-]+@gmail\.com$/.test(email))return alert("Email must be exactly one Gmail address, for example name@gmail.com.");
if(!pass)return alert("Please enter your password.");
if(phone && !/^\d{10}$/.test(phone))return alert("Phone number must contain exactly 10 numbers.");
if(email==="admin@gmail.com"&&pass==="SHREHA@123"){localStorage.setItem("shreha_admin_auth","true");location.href="admin.html";return;}
let u=JSON.parse(localStorage.getItem("shreha_user")||"null")||{name:"SHREHA Customer",email,points:0};
u.name=name;u.email=email;u.phone=phone;
localStorage.setItem("shreha_user",JSON.stringify(u));
location.href="account.html";
}
function logout(){localStorage.removeItem("shreha_user");location.href="login.html"}
function messages(){let a=JSON.parse(localStorage.getItem("shreha_msgs")||"[]");layout(`<div class="title"><span class="eyebrow">PERSONAL SUPPORT</span><h1>Message SHREHA</h1></div><section class="container"><div class="twocol"><div class="panel"><h3>Conversation</h3>${a.map(x=>`<div class="message"><b>${x.from==="admin"?"SHREHA":"You"}</b><p>${x.text}</p></div>`).join("")||"<p class='muted'>Start a conversation with us.</p>"}</div><div class="panel"><h3>Send a message</h3><div class="field"><label>MESSAGE</label><textarea id="msg"></textarea></div><button class="btn primary" onclick="sendMsg()">SEND</button></div></div></section>`)}
function sendMsg(){let a=JSON.parse(localStorage.getItem("shreha_msgs")||"[]");a.push({from:"customer",text:$("#msg").value});localStorage.setItem("shreha_msgs",JSON.stringify(a));messages()}
function gift(){layout(`<div class="title"><span class="eyebrow">SHREHA GIFTING</span><h1>Gift it beautifully</h1><p class="muted">Send clothing to someone else and tell us about their style preferences.</p></div><section class="container"><div class="twocol"><div class="panel"><h3>Recipient details</h3><div class="field"><label>RECIPIENT NAME</label><input></div><div class="field"><label>ADDRESS</label><textarea></textarea></div><div class="field"><label>SIZE / STYLE PREFERENCES</label><textarea placeholder="Favourite colours, sizes, styles..."></textarea></div><div class="field"><label>GIFT MESSAGE</label><textarea></textarea></div><button class="btn primary" onclick="alert('Gift preferences saved.')">SAVE GIFT DETAILS</button></div><div class="panel"><h3>SHREHA Points</h3><p><b>5 points</b> for every order ₹699+.</p><p><b>50 points</b> unlocks a free gift hamper.</p><p><b>100 points</b> unlocks a custom free gift.</p></div></div></section>`)}
function checkout(){let c=cart(),ps=products(),sub=c.reduce((s,i)=>{let p=ps.find(x=>x.id===i.id);return s+p.price*(1-p.offer/100)*i.qty},0),del=sub>=899?0:30;layout(`<div class="title"><span class="eyebrow">CHECKOUT</span><h1>Complete your order</h1></div><section class="container"><div class="twocol"><div class="panel"><h3>Delivery</h3><div class="field"><label>FULL NAME</label><input></div><div class="field"><label>MOBILE</label><input></div><div class="field"><label>ADDRESS</label><textarea></textarea></div><label><input type="checkbox"> This is a gift</label><h3>Payment</h3><select class="select" id="pay" onchange="paymentBox()"><option>UPI / QR</option><option>Credit / Debit Card</option><option>Cash on Delivery</option><option>Net Banking</option><option>Wallet</option></select><div id="paymentbox"></div></div><div class="panel summary"><h3>Order Summary</h3><div class="sum"><span>Subtotal</span><b>${money(sub)}</b></div><div class="sum"><span>Delivery</span><b>${del?"₹30":"FREE"}</b></div><div class="sum total"><span>Total</span><span>${money(sub+del)}</span></div><button class="btn primary" style="width:100%" onclick="placeOrder()">PLACE ORDER</button></div></div></section>`);paymentBox()}
function paymentBox(){let v=$("#pay").value;if(v==="UPI / QR")$("#paymentbox").innerHTML=`<div class="notice" style="text-align:center"><b>Scan & Pay</b><div style="margin:14px auto;width:190px;height:190px;background:#fff;padding:10px;border-radius:12px;box-shadow:0 4px 18px #00000012"><img src="assets/shreha-qr.png" alt="SHREHA QR" style="width:100%;height:100%;object-fit:contain"></div><strong>SHREHA@UPI</strong><br><small>Scan the QR code to continue payment</small></div>`;else if(v.includes("Card"))$("#paymentbox").innerHTML=`<div class="field"><label>CARD NUMBER</label><input placeholder="0000 0000 0000 0000"></div><div class="twocol"><input placeholder="MM/YY"><input placeholder="CVV"></div>`;else if(v==="Net Banking")$("#paymentbox").innerHTML=`<div class="field"><label>SELECT BANK</label><select><option>HDFC Bank</option><option>ICICI Bank</option><option>State Bank of India</option><option>Axis Bank</option></select></div>`;else $("#paymentbox").innerHTML=`<div class="notice">Payment method selected. You can continue to place your order.</div>`}
function placeOrder(){let u=user()||{name:"Customer",email:"customer"};let c=cart(),ps=products();let subtotal=c.reduce((s,i)=>{let p=ps.find(x=>x.id===i.id);return s+(p?p.price*(1-p.offer/100)*i.qty:0)},0);let delivery=subtotal>=899?0:30;let order={number:"SH"+Date.now().toString().slice(-8),date:new Date().toLocaleDateString("en-IN"),items:c.map(i=>{let p=ps.find(x=>x.id===i.id);return {name:p.name,qty:i.qty,price:p.price*(1-p.offer/100)}}),subtotal,delivery,total:subtotal+delivery,customer:u.name||"Customer"};u.points=(u.points||0)+5;localStorage.setItem("shreha_user",JSON.stringify(u));localStorage.setItem("shreha_last_order",JSON.stringify(order));saveCart([]);location.href="order.html"}
function order(){let o=JSON.parse(localStorage.getItem("shreha_last_order")||"null");if(!o)return layout(`<section class="container"><div class="panel" style="max-width:650px;margin:50px auto;text-align:center"><h1>No recent order</h1><a class="btn primary" href="shop.html">SHOP NOW</a></div></section>`);layout(`<section class="container"><div class="panel" style="max-width:820px;margin:30px auto"><div style="text-align:center"><div style="font-size:48px">♡</div><span class="eyebrow">ORDER CONFIRMED</span><h1>Thank you for shopping with SHREHA.</h1><p class="muted">Order #${o.number} • ${o.date}</p></div><div style="border-top:1px solid var(--line);margin-top:25px;padding-top:20px"><h2 style="font-family:'Playfair Display'">SHREHA INVOICE</h2><div class="sum"><span>Customer</span><b>${o.customer}</b></div><div class="tablewrap"><table class="table"><tr><th>ITEM</th><th>QTY</th><th>PRICE</th><th>AMOUNT</th></tr>${o.items.map(i=>`<tr><td>${i.name}</td><td>${i.qty}</td><td>${money(i.price)}</td><td>${money(i.price*i.qty)}</td></tr>`).join("")}</table></div><div style="max-width:360px;margin:18px 0 0 auto"><div class="sum"><span>Subtotal</span><b>${money(o.subtotal)}</b></div><div class="sum"><span>Delivery</span><b>${o.delivery?money(o.delivery):"FREE"}</b></div><div class="sum total"><span>Grand Total</span><span>${money(o.total)}</span></div></div><div class="notice">Thank you for choosing SHREHA. Your order has been placed successfully.</div><div style="text-align:center"><button class="btn soft" onclick="window.print()">PRINT BILL</button> <a class="btn primary" href="shop.html">CONTINUE SHOPPING</a></div></div></div></section>`)}
function loginPage(){layout(`<section class="container"><div class="panel" style="max-width:500px;margin:55px auto"><div style="text-align:center"><span class="eyebrow">WELCOME TO SHREHA</span><h1>Sign in</h1><p class="muted">Access your SHREHA account and continue shopping.</p></div><div class="field"><label>NAME</label><input id="loginName" placeholder="Your name"></div><div class="field"><label>EMAIL</label><input id="loginEmail" type="text" inputmode="email" autocomplete="email" placeholder="name@gmail.com" oninput="this.value=this.value.replace(/[^A-Za-z0-9._@-]/g,'').replace(/@+/g,'@').replace(/@(?=.*@)/g,'')"></div><div class="field"><label>PHONE NUMBER</label><input id="loginPhone" type="tel" inputmode="numeric" maxlength="10" placeholder="10-digit mobile number" oninput="this.value=this.value.replace(/\\D/g,'')"></div>
<div class="field"><label>PASSWORD</label><input id="loginPass" type="password" placeholder="Your password"></div><button class="btn primary" style="width:100%" onclick="commonLogin()">SIGN IN / CREATE ACCOUNT</button><p class="muted" style="font-size:11px;text-align:center;margin-top:15px">Your SHREHA account is protected.</p></div></section>`)}
function admin(){
if(localStorage.getItem("shreha_admin_auth")!=="true"){
layout(`<section class="container"><div class="panel" style="max-width:460px;margin:60px auto"><span class="eyebrow">SHREHA ADMIN</span><h1>Admin Sign In</h1><p class="muted">Sign in to access product, stock, offers, coupons and customer management.</p><div class="field"><label>ADMIN EMAIL</label><input id="adminEmail" type="email" placeholder="admin@gmail.com"></div><div class="field"><label>PASSWORD</label><input id="adminPass" type="password" placeholder="Enter password"></div><button class="btn primary" style="width:100%" onclick="adminLogin()">SIGN IN TO ADMIN PORTAL</button><p class="muted" style="font-size:11px;margin-top:14px">Authorized staff access only.</p></div></section>`);return;}
let ps=products();layout(`<section class="admin"><aside class="aside"><h2 class="adminbrand"><img class="adminmark" src="assets/shreha-mark-dark.png" alt="SHREHA logo mark"><span>SHREHA<br>ADMIN</span></h2><a href="#products">Products</a><a href="#offers">Offers & Coupons</a><a href="#messages">Customer Messages</a><a href="index.html">← Storefront</a><a href="#" onclick="adminLogout();return false">Sign Out</a></aside><main class="adminmain"><div class="stats"><div class="stat">Products<br><b>${ps.length}</b></div><div class="stat">Visible<br><b>${ps.filter(x=>!x.hidden).length}</b></div><div class="stat">Low stock<br><b>${ps.filter(x=>x.stock<10).length}</b></div><div class="stat">Categories<br><b>${CATS.length-1}</b></div></div><div class="panel" id="products" style="margin-top:20px"><h2>Product Management</h2><div class="tablewrap"><table class="table"><tr><th>Product</th><th>Price</th><th>Stock</th><th>Offer</th><th>Visibility</th><th>Actions</th></tr>${ps.map(p=>`<tr><td>${p.name}</td><td><input style="width:80px" id="pr${p.id}" type="number" min="1" max="1500" value="${Math.min(1500,p.price)}"></td><td><input style="width:55px" id="st${p.id}" value="${p.stock}"></td><td><input style="width:55px" id="of${p.id}" value="${p.offer}"></td><td>${p.hidden?"Hidden":"Live"}</td><td><button class="mini" onclick="saveP(${p.id})">Save</button> <button class="mini" onclick="hideP(${p.id})">${p.hidden?"Show":"Hide"}</button> <button class="mini danger" onclick="delP(${p.id})">Delete</button></td></tr>`).join("")}</table></div></div><div class="panel" id="offers" style="margin-top:20px"><h2>Offers & Coupons</h2><div class="twocol"><div><div class="field"><label>COUPON CODE</label><input id="cc"></div><div class="field"><label>DISCOUNT %</label><input id="cp" value="10"></div><button class="btn primary" onclick="coupon()">CREATE COUPON</button></div><div><b>Created Coupons</b><div id="couponlist"></div></div></div></div><div class="panel" id="messages" style="margin-top:20px"><h2>Personal Customer Message</h2><div class="field"><textarea id="am" placeholder="Write a personal message..."></textarea></div><button class="btn primary" onclick="adminMsg()">SEND MESSAGE</button></div></main></section>`)}
function saveP(id){let a=products(),p=a.find(x=>x.id===id);p.price=Math.min(1500,Math.max(1,+$("#pr"+id).value||1));p.stock=+$("#st"+id).value;p.offer=+$("#of"+id).value;saveProducts(a);admin()}function hideP(id){let a=products(),p=a.find(x=>x.id===id);p.hidden=!p.hidden;saveProducts(a);admin()}function delP(id){saveProducts(products().filter(x=>x.id!==id));admin()}function coupon(){let a=JSON.parse(localStorage.getItem("shreha_coupons")||"[]");a.push({code:$("#cc").value.toUpperCase(),pct:+$("#cp").value});localStorage.setItem("shreha_coupons",JSON.stringify(a));alert("Coupon created.");admin()}function adminMsg(){let a=JSON.parse(localStorage.getItem("shreha_msgs")||"[]");a.push({from:"admin",text:$("#am").value});localStorage.setItem("shreha_msgs",JSON.stringify(a));alert("Message sent.");admin()}
function adminLogin(){const email=(document.getElementById("adminEmail")||{}).value||"";const pass=(document.getElementById("adminPass")||{}).value||"";if(email.toLowerCase()==="admin@gmail.com"&&pass==="SHREHA@123"){localStorage.setItem("shreha_admin_auth","true");admin();}else alert("Incorrect admin email or password.");}
function adminLogout(){localStorage.removeItem("shreha_admin_auth");admin()}

function adminGuard(){if(localStorage.getItem("shreha_admin_auth")!=="true"){location.href="login.html";return false}return true}
function adminShell(title,body,active){if(!adminGuard())return;document.querySelector("#app").innerHTML=`<section class="admin"><aside class="aside"><h2 class="adminbrand"><img class="adminmark" src="assets/shreha-mark-dark.png" alt="SHREHA logo mark"><span>SHREHA<br>ADMIN</span></h2><a class="${active==='dashboard'?'active':''}" href="admin.html">Dashboard</a><a class="${active==='products'?'active':''}" href="admin-products.html">Products</a><a class="${active==='orders'?'active':''}" href="admin-orders.html">Orders</a><a class="${active==='customers'?'active':''}" href="admin-customers.html">Customers</a><a class="${active==='offers'?'active':''}" href="admin-offers.html">Offers & Coupons</a><a class="${active==='messages'?'active':''}" href="admin-messages.html">Messages</a><a class="${active==='settings'?'active':''}" href="admin-settings.html">Settings</a><a href="index.html">← Storefront</a><a href="#" onclick="adminLogout();return false">Sign Out</a></aside><main class="adminmain"><div class="title" style="padding:0 0 18px"><span class="eyebrow">SHREHA ADMIN</span><h1>${title}</h1></div>${body}</main></section>`}
function adminDashboard(){let ps=products();adminShell("Dashboard",`<div class="stats"><div class="stat">Products<br><b>${ps.length}</b></div><div class="stat">Visible<br><b>${ps.filter(x=>!x.hidden).length}</b></div><div class="stat">Low stock<br><b>${ps.filter(x=>x.stock<10).length}</b></div><div class="stat">Categories<br><b>${CATS.length-1}</b></div></div><div class="panel" style="margin-top:20px"><h2>Quick overview</h2><p class="muted">Manage your SHREHA store using the separate admin sections.</p><div class="collections"><a class="collection pink" href="admin-products.html"><h3>Products</h3><p>Edit, hide, delete, stock and pricing.</p></a><a class="collection lav" href="admin-orders.html"><h3>Orders</h3><p>Review recent orders and fulfilment.</p></a><a class="collection sage" href="admin-customers.html"><h3>Customers</h3><p>Customer accounts and points.</p></a></div></div>`,`dashboard`)}
function adminProducts(){let ps=products();adminShell("Products",`<div class="panel"><div class="toolbar"><b>${ps.length} products</b><a class="btn primary" href="shop.html">View Store</a></div><div class="tablewrap"><table class="table"><tr><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Offer</th><th>Visibility</th><th>Actions</th></tr>${ps.map(p=>`<tr><td>${p.name}</td><td>${p.cat}</td><td><input style="width:80px" id="pr${p.id}" type="number" min="1" max="1500" value="${Math.min(1500,p.price)}"></td><td><input style="width:55px" id="st${p.id}" value="${p.stock}"></td><td><input style="width:55px" id="of${p.id}" value="${p.offer}"></td><td>${p.hidden?"Hidden":"Live"}</td><td><button class="mini" onclick="saveP2(${p.id})">Save</button> <button class="mini" onclick="hideP2(${p.id})">${p.hidden?"Show":"Hide"}</button> <button class="mini danger" onclick="delP2(${p.id})">Delete</button></td></tr>`).join("")}</table></div></div>`,`products`)}
function saveP2(id){let a=products(),p=a.find(x=>x.id===id);p.price=Math.min(1500,Math.max(1,+document.getElementById("pr"+id).value||1));p.stock=+document.getElementById("st"+id).value;p.offer=+document.getElementById("of"+id).value;saveProducts(a);adminProducts()}function hideP2(id){let a=products(),p=a.find(x=>x.id===id);p.hidden=!p.hidden;saveProducts(a);adminProducts()}function delP2(id){saveProducts(products().filter(x=>x.id!==id));adminProducts()}
function adminOrders(){let o=JSON.parse(localStorage.getItem("shreha_orders")||"[]"),last=JSON.parse(localStorage.getItem("shreha_last_order")||"null");if(last&&!o.some(x=>x.number===last.number)){o.unshift(last);localStorage.setItem("shreha_orders",JSON.stringify(o))}adminShell("Orders",`<div class="panel"><div class="tablewrap"><table class="table"><tr><th>Order</th><th>Date</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th></tr>${o.length?o.map(x=>`<tr><td>${x.number}</td><td>${x.date}</td><td>${x.customer}</td><td>${x.items.length}</td><td>${money(x.total)}</td><td><select><option>Placed</option><option>Processing</option><option>Shipped</option><option>Delivered</option></select></td></tr>`).join(""):"<tr><td colspan='6'>No orders yet.</td></tr>"}</table></div></div>`,`orders`)}
function adminCustomers(){let u=JSON.parse(localStorage.getItem("shreha_user")||"null");adminShell("Customers",`<div class="panel"><h2>Customer accounts</h2>${u?`<div class="message"><b>${u.name}</b><p>${u.email}</p><p>SHREHA Points: <b>${u.points||0}</b></p></div>`:"<p class='muted'>No customer account has been created on this browser yet.</p>"}</div>`,`customers`)}
function adminOffers(){let a=JSON.parse(localStorage.getItem("shreha_coupons")||"[]");adminShell("Offers & Coupons",`<div class="twocol"><div class="panel"><h2>Create Coupon</h2><div class="field"><label>COUPON CODE</label><input id="cc"></div><div class="field"><label>DISCOUNT %</label><input id="cp" value="10"></div><button class="btn primary" onclick="coupon2()">CREATE COUPON</button></div><div class="panel"><h2>Active Coupons</h2>${a.length?a.map(x=>`<div class="message"><b>${x.code}</b><span style="float:right">${x.pct}% OFF</span></div>`).join(""):"<p class='muted'>No coupons yet.</p>"}</div></div>`,`offers`)}
function coupon2(){let a=JSON.parse(localStorage.getItem("shreha_coupons")||"[]"),code=(document.getElementById("cc").value||"").trim().toUpperCase(),pct=+document.getElementById("cp").value;if(!code)return alert("Enter a coupon code.");a.push({code,pct});localStorage.setItem("shreha_coupons",JSON.stringify(a));adminOffers()}
function adminMessages(){let a=JSON.parse(localStorage.getItem("shreha_msgs")||"[]");adminShell("Customer Messages",`<div class="twocol"><div class="panel"><h2>Conversation</h2>${a.length?a.map(x=>`<div class="message"><b>${x.from==='admin'?'SHREHA':'Customer'}</b><p>${x.text}</p></div>`).join(""):"<p class='muted'>No messages yet.</p>"}</div><div class="panel"><h2>Send Personal Message</h2><div class="field"><label>MESSAGE</label><textarea id="am" placeholder="Write a personal message..."></textarea></div><button class="btn primary" onclick="adminMsg2()">SEND MESSAGE</button></div></div>`,`messages`)}
function adminMsg2(){let a=JSON.parse(localStorage.getItem("shreha_msgs")||"[]");a.push({from:"admin",text:document.getElementById("am").value});localStorage.setItem("shreha_msgs",JSON.stringify(a));adminMessages()}
function adminSettings(){adminShell("Settings",`<div class="panel"><h2>Store Settings</h2><div class="field"><label>FREE DELIVERY ABOVE</label><input value="899"></div><div class="field"><label>DELIVERY BELOW THRESHOLD</label><input value="30"></div><div class="field"><label>POINTS PER ELIGIBLE ORDER</label><input value="5"></div><div class="notice">Changes shown here are part of the college-project storefront settings.</div></div>`,`settings`)}
const page=document.body.dataset.page;if(page==="home")home();else if(page==="shop")shop();else if(page==="product")product();else if(page==="cart")cartPage();else if(page==="wishlist")wishlistPage();else if(page==="account")account();else if(page==="login")loginPage();else if(page==="messages")messages();else if(page==="gift")gift();else if(page==="checkout")checkout();else if(page==="order")order();else if(page==="admin")adminDashboard();else if(page==="admin-products")adminProducts();else if(page==="admin-orders")adminOrders();else if(page==="admin-customers")adminCustomers();else if(page==="admin-offers")adminOffers();else if(page==="admin-messages")adminMessages();else if(page==="admin-settings")adminSettings();
